# Generated by Django 5.1.6 on 2025-02-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=20, unique=True)),
                ('courseName', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
